apiVersion: tekton.dev/v1
kind: PipelineRun
metadata:
  name: {{ values.name }}-gitops-on-pull-request
  annotations:
    pipelinesascode.tekton.dev/on-event: "[pull_request]"
    pipelinesascode.tekton.dev/on-target-branch: "[{{ values.defaultBranch }}]" 
    pipelinesascode.tekton.dev/pipeline: "{{values.rawUrl}}/pac/pipelines/gitops-pull-request-ai-rhdh.yaml"
    pipelinesascode.tekton.dev/task-0: "{{values.rawUrl}}/pac/tasks/git-clone.yaml"
spec:
  params:
  - name: git-url
    value: '{{repo_url}}'   
  - name: revision
    value: '{{revision}}'     
  - name: target-branch
    value: '{{target_branch}}'
  pipelineRef:
    name: gitops-pull-request
  workspaces:
    - name: git-auth
      secret:
        secretName: "{{ git_auth_secret }}"
    - name: workspace
      volumeClaimTemplate:
        spec:
          accessModes:
          - ReadWriteOnce
          resources:
            requests:
              storage: 1Gi
