apiVersion: tekton.dev/v1
kind: Pipeline
metadata:
  name: gitops-pull-request
spec:
  params:
  - description: Gitops repo url
    name: git-url
    type: string
  - default: ""
    description: Gitops repo revision
    name: revision
    type: string
  - default: main
    description: The target branch for the pull request
    name: target-branch
    type: string
  - default: "true"
    description: Should the pipeline fail when there are SBOMs to upload but Trustification
      is not properly configured (i.e. the secret is missing or doesn't have all the
      required keys)?
    name: fail-if-trustification-not-configured
    type: string
  - default: k8s://$(context.pipelineRun.namespace)/cosign-pub
    description: The public key that EC should use to verify signatures
    name: ec-public-key
    type: string
  - default: http://rekor-server.rhtap.svc
    description: The Rekor host that EC should use to look up transparency logs
    name: ec-rekor-host
    type: string
  - default: http://tuf.rhtap.svc
    description: The TUF mirror that EC should use
    name: ec-tuf-mirror
    type: string
  tasks:
  - name: clone-repository
    params:
    - name: url
      value: $(params.git-url)
    - name: revision
      value: $(params.revision)
    - name: fetchTags
      value: "true"
    taskRef:
      name: git-clone
    workspaces:
    - name: output
      workspace: workspace
    - name: basic-auth
      workspace: git-auth
  - name: get-images-to-upload-sbom
    params:
    - name: TARGET_BRANCH
      value: $(params.target-branch)
    - name: FROM_ENVIRONMENTS
      value:
      - stage
      - prod
    runAfter:
    - clone-repository
    taskRef:
      name: gather-deploy-images
    workspaces:
    - name: source
      workspace: workspace
- name: download-sboms
  params:
  - name: IMAGES
    value: $(tasks.get-images-to-upload-sbom.results.IMAGES_TO_VERIFY)
  - name: SBOMS_DIR
    value: sboms
  - name: PUBLIC_KEY
    value: $(params.ec-public-key)
  - name: REKOR_HOST
    value: $(params.ec-rekor-host)
  - name: TUF_MIRROR
    value: $(params.ec-tuf-mirror)
  runAfter:
  - get-images-to-upload-sbom
  taskRef:
    name: download-sbom-from-url-in-attestation
  when:
  - input: $(tasks.get-images-to-upload-sbom.results.IMAGES_TO_VERIFY)
    operator: notin
    values:
    - ""
  workspaces:
  - name: sboms
    workspace: workspace
- name: upload-sboms-to-trustification
  params:
  - name: SBOMS_DIR
    value: sboms
  - name: TRUSTIFICATION_SECRET_NAME
    value: $(params.trustification-secret-name)
  - name: FAIL_IF_TRUSTIFICATION_NOT_CONFIGURED
    value: $(params.fail-if-trustification-not-configured)
  runAfter:
  - download-sboms
  taskRef:
    name: upload-sbom-to-trustification
  when:
  - input: $(tasks.get-images-to-upload-sbom.results.IMAGES_TO_VERIFY)
    operator: notin
    values:
    - ""
  workspaces:
  - name: sboms
    workspace: workspace